from datetime import datetime

DATE_FROM: datetime = datetime(2023, 11, 6)
DATE_TO: datetime = datetime(2025, 11, 6)

HOURS_IN_COURSE = 30
MAX_AMOUNT_OF_INSTRUCTORS: int = 100
AMOUNT_OF_CARS: int = 20
MAX_AMOUNT_OF_STUDENTS: int = 1000

STUDENT_AGE_MIN = 18
STUDENT_AGE_MAX = 30

INSTRUCTOR_AGE_MIN = 22
INSTRUCTOR_AGE_MAX = 50
INSTRUCTOR_YEARS_EXPERIENCE_MAX = 22

