from datetime import datetime

VERBOSE: bool = False

DATE_FROM: datetime = datetime(2023, 1, 1)
DATE_TO: datetime = datetime(2023, 6, 1)

HOURS_IN_COURSE = 30
MAX_AMOUNT_OF_INSTRUCTORS: int = 500
AMOUNT_OF_CARS: int = 500
MAX_AMOUNT_OF_STUDENTS: int = 10000

STUDENT_AGE_MIN = 18
STUDENT_AGE_MAX = 30

INSTRUCTOR_AGE_MIN = 22
INSTRUCTOR_AGE_MAX = 50
INSTRUCTOR_YEARS_EXPERIENCE_MAX = 22

