from datetime import datetime, timedelta

VERBOSE: bool = False
PERF: bool = False

DATE_FROM: datetime = datetime(2023, 1, 1)
TOTAL_DAYS = 100
DATE_TO: datetime = DATE_FROM + timedelta(days=TOTAL_DAYS)

HOURS_IN_COURSE = 30
MAX_AMOUNT_OF_INSTRUCTORS: int = 500
AMOUNT_OF_CARS: int = 500
MAX_AMOUNT_OF_STUDENTS: int = 10000

STUDENT_AGE_MIN = 18
STUDENT_AGE_MAX = 30

INSTRUCTOR_AGE_MIN = 22
INSTRUCTOR_AGE_MAX = 50
INSTRUCTOR_YEARS_EXPERIENCE_MAX = 22

